[build]
  publish = "_site"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
