backend:
  name: git-gateway
  branch: main

media_folder: "content/media"
public_folder: "/content/media"

collections:
  - name: "media"
    label: "Mediathek"
    folder: "content/media"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Bild", name: "image", widget: "image" }
